### ISSUE TITLE
 exchange对adm的取值出现错误.

### ISSUE THREAD

**Issue by Tate-ad** [adleida/paxp2#1]
**exchange接受到两家dsp返回bid-response后**

1.一家dsp返回两个物料,一个没有adm.id
2.另一家返回正常

没有选出最佳方案,具体请查看032-1 README.md文件

``` yaml

---
category: wrong/format/032-1
author: xiaojian
datetime: 2015-05-07

---

## summary

两家dsp返回物料,一家dsp没有adm.id字段

## detail

1. 修改config.yaml文件
1. 编写request文件和response文件
1. 编写result文件
1. 运行tkit

## changelog

- 2015-04-23: 初始版本
- 2015-04-23: 初始版本
```
